url: https://phatque.github.io/

# Site settings
title: Phat + Que
email: vophat0607@gmail.com
description: "Welcome to our wedding."


# Build settings
markdown: kramdown
permalink: pretty

#include: ['_en_pages', '_fr_pages']
